[tool.pdm]
version = { source = "file", path = "src/brf2ebrf/__init__.py" }
[tool.pdm.scripts]
exe_cli = "python -m nuitka --standalone {args} src/brf2ebrf/scripts/to_ebrf.py"
test = "pytest"
[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.3.1",
]
exe = [
    "nuitka>=1.7.9",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
testpaths = ["tests",]
[project]
dynamic = ["version"]
name = "brf2ebrf"
description = "A tool for converting BRF to eBRF."
authors = [
    {name = "Michael Whapples", email = "mwhapples@aph.org"},
]
dependencies = [
    "pypdf2>=3.0.1",
    "regex>=2023.8.8",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MPL-2.0"}

[project.scripts]
brf2unicode = "brf2ebrf.scripts.to_unicode:main"
brf2ebrf = "brf2ebrf.scripts.to_ebrf:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
