[tool.pdm]
version = { source = "file", path = "src/brf2ebrf/__init__.py" }

[project]
dynamic = ["version"]
name = "brf2ebrf"
description = "A tool for converting BRF to eBRF."
authors = [
    {name = "Michael Whapples", email = "mwhapples@aph.org"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
