[tool.pdm]
version = { source = "file", path = "src/brf2ebrf/__init__.py" }
[tool.pdm.scripts]
test = "pytest"
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.3.1",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
testpaths = ["tests",]
[project]
dynamic = ["version"]
name = "brf2ebrf"
description = "A tool for converting BRF to eBRF."
authors = [
    {name = "Michael Whapples", email = "mwhapples@aph.org"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
